# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Yi Zhang / Academic Portfolio"
title_separator          : "-"
name                     : &name "Yi Zhang"
description              : &description "Yi Zhang's academic portfolio in Data Science, Computer Vision, and NLP"
url                      : https://yiiiiizhang.github.io   # GitHub Pages 默认域名
baseurl                  : "" 
repository               : "YiiiiZhang/YiiiiZhang.github.io"   # 你的 GitHub Pages 仓库名（如不同请告诉我）

# Site Author
author:
  avatar           : "profile.png"
  name             : "Yi Zhang"
  bio              : "Graduate student in Data Science with research interests in Computer Vision, Emotion Recognition, and NLP."
  location         : "Nuremberg, Germany"
  employer         : "Social Data Science and AI Lab, LMU Munich"
  uri              : "https://sites.google.com/view/yizhang/%E9%A6%96%E9%A1%B5"
  email            : "HBen_ZY@outlook.com" 

  googlescholar    : "https://scholar.google.com/citations?user=Lxw9aQ8AAAAJ&hl=en"
  github           : "YiiiiZhang"

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"

comments:
  provider               : 

atom_feed:
  hide                   : false
  path                   :

# Social Sharing
social:
  type                   : Person
  name                   : "Yi Zhang"
  links:
    - "https://sites.google.com/view/yizhang/%E9%A6%96%E9%A1%B5"
    - "https://scholar.google.com/citations?user=Lxw9aQ8AAAAJ&hl=en"
    - "https://github.com/YiiiiZhang"

analytics:
  provider               : "false"

include:
  - .htaccess
  - _pages
  - files

exclude:
  - node_modules
  - vendor
  - README
  - Gemfile

# Markdown & Build settings
markdown: kramdown
highlighter: rouge

collections:
  teaching:
    output: true
  publications:
    output: true
  portfolio:
    output: true
  talks:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  style: compressed

permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development
